name: Deploy ke GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build app
        run: |
          mkdir -p dist
          cp index.html dist/index.html
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Deploy ke GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./dist
