
name: Access Firestore

on:
  workflow_dispatch:

jobs:
  firestore_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Access Firestore via REST API
        env:
          FIREBASE_PROJECT_ID: your-project-id
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        run: |
          curl -X GET \
            "https://firestore.googleapis.com/v1/projects/$FIREBASE_PROJECT_ID/databases/(default)/documents/your-collection" \
            -H "Authorization: Bearer $FIREBASE_API_KEY"
