name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Jalankan setiap kali ada push ke branch main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Build project (optional, kalau ada build step)
        run: echo "No build step, just static files"

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"
