
name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Build project (optional)
        run: echo "No build step, just static files"

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting:work-order-7ad3c-470100 --project work-order-7ad3c
